use crate::database::{PragmaDefinition, PragmaType, p_definition};

pub const PRAGMA_DEFINITIONS: &[PragmaDefinition] = &[
    p_definition(
        "analysis_limit",
        "https://www.sqlite.org/pragma.html#pragma_analysis_limit",
        PragmaType::Integer,
    ),
    p_definition(
        "application_id",
        "https://www.sqlite.org/pragma.html#application_id",
        PragmaType::Integer,
    ),
    p_definition(
        "auto_vacuum",
        "https://www.sqlite.org/pragma.html#auto_vacuum",
        PragmaType::Enum {
            values: &["0", "NONE", "1", "FULL", "2", "INCREMENTAL"],
        },
    ),
    p_definition(
        "automatic_index",
        "https://www.sqlite.org/pragma.html#automatic_index",
        PragmaType::Boolean,
    ),
    p_definition(
        "cache_size",
        "https://www.sqlite.org/pragma.html#cache_size",
        PragmaType::Integer,
    ),
    p_definition(
        "case_sensitive_like",
        "https://www.sqlite.org/pragma.html#case_sensitive_like",
        PragmaType::Boolean,
    ),
    p_definition(
        "cell_size_check",
        "https://www.sqlite.org/pragma.html#cell_size_check",
        PragmaType::Boolean,
    ),
    p_definition(
        "checkpoint_fullfsync",
        "https://www.sqlite.org/pragma.html#checkpoint_fullfsync",
        PragmaType::Boolean,
    ),
    p_definition(
        "count_changes",
        "https://www.sqlite.org/pragma.html#count_changes",
        PragmaType::Boolean,
    ),
    p_definition(
        "data_store_directory",
        "https://www.sqlite.org/pragma.html#data_store_directory",
        PragmaType::Text,
    ),
    p_definition(
        "default_cache_size",
        "https://www.sqlite.org/pragma.html#default_cache_size",
        PragmaType::Integer,
    ),
    p_definition(
        "defer_foreign_keys",
        "https://www.sqlite.org/pragma.html#defer_foreign_keys",
        PragmaType::Boolean,
    ),
    p_definition(
        "empty_result_callbacks",
        "https://www.sqlite.org/pragma.html#empty_result_callbacks",
        PragmaType::Boolean,
    ),
    p_definition(
        "encoding",
        "https://www.sqlite.org/pragma.html#encoding",
        PragmaType::Enum {
            values: &["UTF-8", "UTF-16", "UTF-16le", "UTF-16be"],
        },
    ),
    p_definition(
        "foreign_keys",
        "https://www.sqlite.org/pragma.html#foreign_keys",
        PragmaType::Boolean,
    ),
    p_definition(
        "full_column_names",
        "https://www.sqlite.org/pragma.html#full_column_names",
        PragmaType::Boolean,
    ),
    p_definition(
        "fullfsync",
        "https://www.sqlite.org/pragma.html#fullfsync",
        PragmaType::Boolean,
    ),
    p_definition(
        "hard_heap_limit",
        "https://www.sqlite.org/pragma.html#hard_heap_limit",
        PragmaType::Integer,
    ),
    p_definition(
        "ignore_check_constraints",
        "https://www.sqlite.org/pragma.html#ignore_check_constraints",
        PragmaType::Boolean,
    ),
    p_definition(
        "journal_mode",
        "https://www.sqlite.org/pragma.html#journal_mode",
        PragmaType::Enum {
            values: &["DELETE", "TRUNCATE", "PERSIST", "MEMORY", "WAL", "OFF"],
        },
    ),
    p_definition(
        "journal_size_limit",
        "https://www.sqlite.org/pragma.html#journal_size_limit",
        PragmaType::Integer,
    ),
    p_definition(
        "legacy_alter_table",
        "https://www.sqlite.org/pragma.html#legacy_alter_table",
        PragmaType::Boolean,
    ),
    p_definition(
        "locking_mode",
        "https://www.sqlite.org/pragma.html#locking_mode",
        PragmaType::Enum {
            values: &["NORMAL", "EXCLUSIVE"],
        },
    ),
    p_definition(
        "max_page_count",
        "https://www.sqlite.org/pragma.html#max_page_count",
        PragmaType::Integer,
    ),
    p_definition(
        "mmap_size",
        "https://www.sqlite.org/pragma.html#mmap_size",
        PragmaType::Integer,
    ),
    p_definition(
        "page_size",
        "https://www.sqlite.org/pragma.html#page_size",
        PragmaType::Integer,
    ),
    p_definition(
        "parser_trace",
        "https://www.sqlite.org/pragma.html#parser_trace",
        PragmaType::Boolean,
    ),
    p_definition(
        "query_only",
        "https://www.sqlite.org/pragma.html#query_only",
        PragmaType::Boolean,
    ),
    p_definition(
        "read_uncommitted",
        "https://www.sqlite.org/pragma.html#read_uncommitted",
        PragmaType::Boolean,
    ),
    p_definition(
        "recursive_triggers",
        "https://www.sqlite.org/pragma.html#recursive_triggers",
        PragmaType::Boolean,
    ),
    p_definition(
        "reverse_unordered_selects",
        "https://www.sqlite.org/pragma.html#reverse_unordered_selects",
        PragmaType::Boolean,
    ),
    p_definition(
        "secure_delete",
        "https://www.sqlite.org/pragma.html#secure_delete",
        PragmaType::Enum {
            values: &["true", "false", "FAST"],
        },
    ),
    p_definition(
        "short_column_names",
        "https://www.sqlite.org/pragma.html#short_column_names",
        PragmaType::Boolean,
    ),
    p_definition(
        "soft_heap_limit",
        "https://www.sqlite.org/pragma.html#soft_heap_limit",
        PragmaType::Integer,
    ),
    p_definition(
        "synchronous",
        "https://www.sqlite.org/pragma.html#synchronous",
        PragmaType::Enum {
            values: &["0", "OFF", "1", "NORMAL", "2", "FULL", "3", "EXTRA"],
        },
    ),
    p_definition(
        "temp_store",
        "https://www.sqlite.org/pragma.html#temp_store",
        PragmaType::Enum {
            values: &["0", "DEFAULT", "1", "FILE", "2", "MEMORY"],
        },
    ),
    p_definition(
        "temp_store_directory",
        "https://www.sqlite.org/pragma.html#temp_store_directory",
        PragmaType::Text,
    ),
    p_definition(
        "threads",
        "https://www.sqlite.org/pragma.html#threads",
        PragmaType::Integer,
    ),
    p_definition(
        "trusted_schema",
        "https://www.sqlite.org/pragma.html#trusted_schema",
        PragmaType::Boolean,
    ),
    p_definition(
        "user_version",
        "https://www.sqlite.org/pragma.html#user_version",
        PragmaType::Integer,
    ),
    p_definition(
        "vdbe_addoptrace",
        "https://www.sqlite.org/pragma.html#vdbe_addoptrace",
        PragmaType::Boolean,
    ),
    p_definition(
        "vdbe_debug",
        "https://www.sqlite.org/pragma.html#vdbe_debug",
        PragmaType::Boolean,
    ),
    p_definition(
        "vdbe_listing",
        "https://www.sqlite.org/pragma.html#vdbe_listing",
        PragmaType::Boolean,
    ),
    p_definition(
        "vdbe_trace",
        "https://www.sqlite.org/pragma.html#vdbe_trace",
        PragmaType::Boolean,
    ),
    p_definition(
        "wal_autocheckpoint",
        "https://www.sqlite.org/pragma.html#wal_autocheckpoint",
        PragmaType::Integer,
    ),
    p_definition(
        "writable_schema",
        "https://www.sqlite.org/pragma.html#writable_schema",
        PragmaType::Boolean,
    ),
];
